variables:
  DENO_DEPLOY_TOKEN:
    description: "Access token for Deno Deploy"

stages:
  - check
  - deploy

default:
  image: denoland/deno:alpine

check-job:
  stage: check
  script:
    - deno fmt --check
    - deno lint
    - deno check app/main.ts

deploy-job:
  stage: deploy
  rules:
    - if: $DENO_DEPLOY_TOKEN
  script:
    - deno task deploy --prod
  environment: production
